#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AkavacheExplorer.Droid.Resource", IsApplication=false)]

namespace AkavacheExplorer.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040000
			public static int explorer_content_radio_group = 2130968576;
			
			// aapt resource value: 0x7f040005
			public static int explorer_data_text_view = 2130968581;
			
			// aapt resource value: 0x7f040006
			public static int explorer_image_view = 2130968582;
			
			// aapt resource value: 0x7f040007
			public static int explorer_list_view = 2130968583;
			
			// aapt resource value: 0x7f040003
			public static int explorer_radio_image = 2130968579;
			
			// aapt resource value: 0x7f040001
			public static int explorer_radio_json = 2130968577;
			
			// aapt resource value: 0x7f040002
			public static int explorer_radio_text = 2130968578;
			
			// aapt resource value: 0x7f040004
			public static int explorer_text_scroll_view = 2130968580;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public static int explorer_activity_data = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int explorer_activity_keys = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int explorer_list_item = 2130837506;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030001
			public static int explorer_title_local_machine = 2130903041;
			
			// aapt resource value: 0x7f030004
			public static int explorer_title_view_as_image = 2130903044;
			
			// aapt resource value: 0x7f030002
			public static int explorer_title_view_as_json = 2130903042;
			
			// aapt resource value: 0x7f030003
			public static int explorer_title_view_as_text = 2130903043;
			
			// aapt resource value: 0x7f030000
			public static int library_name = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
