#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AkavacheExplorerSample.Droid.Resource", IsApplication=true)]

namespace AkavacheExplorerSample.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::AkavacheExplorer.Droid.Resource.Id.contentRadioGroup = global::AkavacheExplorerSample.Droid.Resource.Id.contentRadioGroup;
			global::AkavacheExplorer.Droid.Resource.Id.datatTextView = global::AkavacheExplorerSample.Droid.Resource.Id.datatTextView;
			global::AkavacheExplorer.Droid.Resource.Id.imageView = global::AkavacheExplorerSample.Droid.Resource.Id.imageView;
			global::AkavacheExplorer.Droid.Resource.Id.listView = global::AkavacheExplorerSample.Droid.Resource.Id.listView;
			global::AkavacheExplorer.Droid.Resource.Id.radio_image = global::AkavacheExplorerSample.Droid.Resource.Id.radio_image;
			global::AkavacheExplorer.Droid.Resource.Id.radio_json = global::AkavacheExplorerSample.Droid.Resource.Id.radio_json;
			global::AkavacheExplorer.Droid.Resource.Id.radio_text = global::AkavacheExplorerSample.Droid.Resource.Id.radio_text;
			global::AkavacheExplorer.Droid.Resource.Id.textScrollView = global::AkavacheExplorerSample.Droid.Resource.Id.textScrollView;
			global::AkavacheExplorer.Droid.Resource.Layout.activity_data = global::AkavacheExplorerSample.Droid.Resource.Layout.activity_data;
			global::AkavacheExplorer.Droid.Resource.Layout.activity_keys = global::AkavacheExplorerSample.Droid.Resource.Layout.activity_keys;
			global::AkavacheExplorer.Droid.Resource.Layout.list_item = global::AkavacheExplorerSample.Droid.Resource.Layout.list_item;
			global::AkavacheExplorer.Droid.Resource.String.library_name = global::AkavacheExplorerSample.Droid.Resource.String.library_name;
			global::AkavacheExplorer.Droid.Resource.String.title_local_machine = global::AkavacheExplorerSample.Droid.Resource.String.title_local_machine;
			global::AkavacheExplorer.Droid.Resource.String.title_view_as_image = global::AkavacheExplorerSample.Droid.Resource.String.title_view_as_image;
			global::AkavacheExplorer.Droid.Resource.String.title_view_as_json = global::AkavacheExplorerSample.Droid.Resource.String.title_view_as_json;
			global::AkavacheExplorer.Droid.Resource.String.title_view_as_text = global::AkavacheExplorerSample.Droid.Resource.String.title_view_as_text;
			global::Splat.Resource.String.library_name = global::AkavacheExplorerSample.Droid.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int image = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int contentRadioGroup = 2131099648;
			
			// aapt resource value: 0x7f060005
			public const int datatTextView = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int imageView = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int listView = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int openButton = 2131099656;
			
			// aapt resource value: 0x7f060003
			public const int radio_image = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int radio_json = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int radio_text = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int textScrollView = 2131099652;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int activity_data = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int activity_keys = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int list_item = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Main = 2130968579;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050006
			public const int app_name = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int hello = 2131034117;
			
			// aapt resource value: 0x7f050000
			public const int library_name = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int title_local_machine = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int title_view_as_image = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int title_view_as_json = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int title_view_as_text = 2131034115;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
