#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AkavacheExplorerSample.Droid.Resource", IsApplication=true)]

namespace AkavacheExplorerSample.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::AkavacheExplorer.Droid.Resource.Id.datatTextView = global::AkavacheExplorerSample.Droid.Resource.Id.datatTextView;
			global::AkavacheExplorer.Droid.Resource.Id.listView = global::AkavacheExplorerSample.Droid.Resource.Id.listView;
			global::AkavacheExplorer.Droid.Resource.Layout.activity_data = global::AkavacheExplorerSample.Droid.Resource.Layout.activity_data;
			global::AkavacheExplorer.Droid.Resource.Layout.activity_keys = global::AkavacheExplorerSample.Droid.Resource.Layout.activity_keys;
			global::AkavacheExplorer.Droid.Resource.Layout.list_item = global::AkavacheExplorerSample.Droid.Resource.Layout.list_item;
			global::AkavacheExplorer.Droid.Resource.String.library_name = global::AkavacheExplorerSample.Droid.Resource.String.library_name;
			global::Splat.Resource.String.library_name = global::AkavacheExplorerSample.Droid.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int datatTextView = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int listView = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int openButton = 2131034114;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_data = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int activity_keys = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int list_item = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
